services:
  mysql:
    image: mysql:8.4
    container_name: danmakux-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: danmakux
      MYSQL_USER: danmakux
      MYSQL_PASSWORD: danmakux
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7.2
    container_name: danmakux-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
